# Generated by Django 3.2.7 on 2021-12-27 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_tblphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtblentityaddress',
            name='AddressIDF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tbladdress'),
        ),
        migrations.AlterField(
            model_name='rtblentityaddress',
            name='EntityIDF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tblentity'),
        ),
        migrations.AlterField(
            model_name='rtblentityemail',
            name='EmailIDF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tblemail'),
        ),
        migrations.AlterField(
            model_name='rtblentityemail',
            name='EntityIDF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tblentity'),
        ),
        migrations.AlterField(
            model_name='tblcompany',
            name='EntityIDF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tblentity'),
        ),
        migrations.AlterField(
            model_name='tblcompany',
            name='HeadcountIDF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tblheadcount'),
        ),
        migrations.AlterField(
            model_name='tblentityphone',
            name='EntityIDF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tblentity'),
        ),
        migrations.AlterField(
            model_name='tblentityphone',
            name='PhoneIDF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tblphone'),
        ),
        migrations.AlterField(
            model_name='tblentitysocialmedia',
            name='EntityIDF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tblentity'),
        ),
        migrations.AlterField(
            model_name='tblentitysocialmedia',
            name='SocialMediaIDF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tblsocialmedia'),
        ),
        migrations.AlterField(
            model_name='tblphoto',
            name='EntityIDF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tblentity'),
        ),
    ]
