# Generated by Django 3.2.7 on 2021-12-27 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20211227_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblentity',
            name='CreatedAT',
            field=models.DateField(default=datetime.date(2021, 12, 27)),
        ),
    ]
