# Generated by Django 3.2.7 on 2022-01-10 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0030_alter_tblentity_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='stblSkill',
            fields=[
                ('SkillID', models.AutoField(primary_key=True, serialize=False)),
                ('Skill', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='stblStatus',
            fields=[
                ('StatusID', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='tblperson',
            name='About',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tblperson',
            name='experience',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblphoto',
            name='Photo',
            field=models.ImageField(default='../Static/avatar.jpg', upload_to='images'),
        ),
        migrations.CreateModel(
            name='tblEntitySkill',
            fields=[
                ('EntitySkillID', models.AutoField(primary_key=True, serialize=False)),
                ('EntityIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tblentity')),
                ('SkillIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stblskill')),
            ],
        ),
        migrations.CreateModel(
            name='tblEntityCallDetails',
            fields=[
                ('EntityCallDetailsID', models.AutoField(primary_key=True, serialize=False)),
                ('About', models.TextField(null=True)),
                ('Date', models.DateTimeField()),
                ('CreatedAT', models.DateTimeField(auto_now_add=True)),
                ('CreatedBY', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('EntityIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tblentity')),
                ('StatusIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stblstatus')),
            ],
        ),
        migrations.CreateModel(
            name='tblDocument',
            fields=[
                ('DocumentID', models.AutoField(primary_key=True, serialize=False)),
                ('Document', models.FileField(upload_to='Documents')),
                ('EntityIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tblentity')),
            ],
        ),
        migrations.AddField(
            model_name='tblperson',
            name='StatusIDF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stblstatus'),
        ),
    ]
