# Generated by Django 3.2.7 on 2022-01-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20220110_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stblstatus',
            options={'verbose_name_plural': 'stbl Status'},
        ),
        migrations.AlterModelOptions(
            name='tblentitycalldetails',
            options={'verbose_name_plural': 'tbl Entity Call Details'},
        ),
        migrations.RenameField(
            model_name='tblperson',
            old_name='experience',
            new_name='Experiance',
        ),
        migrations.AlterField(
            model_name='tblentitycalldetails',
            name='About',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblperson',
            name='About',
            field=models.TextField(blank=True, null=True),
        ),
    ]
