# Generated by Django 3.2.7 on 2022-01-12 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20220111_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblentitycalldetails',
            old_name='About',
            new_name='AboutCall',
        ),
        migrations.RenameField(
            model_name='tblperson',
            old_name='About',
            new_name='AboutPerson',
        ),
    ]
